### ISSUE TITLE
Completed module 3 assignments

### ISSUE THREAD

**Issue by adnanwijayarso** [ds4owd-001/md-03-assignments-adnanwijayarso#1]
Hello @larnsce @mianzg @sskorik01, I have completed part 1 of the module 3 assignments (3a & 3b)!

**Comment by larnsce** [comment]
Great job, @adnanwijayarso ! You can see a comparison of what was deleted/edited (red - left side) and was added (green - right side) here: https://github.com/ds4owd-001/md-03-assignments-adnanwijayarso/commit/d9538e5905cf5f27e34bdb5128e79a38e79f4532

I have added some comments. On each line, one can add comments. A bit like you would do in MS Word with comments and track changes.

I will close the issue for you now.
